### ISSUE TITLE
Cannot load from file

### ISSUE THREAD

**Issue by delebash** [besanta/UEJsonParser#2]
I am using the node Create Json From Data File but it keeps returning false for successful load.

The json is valid.  Here is the test file.

[test.zip](https://github.com/besanta/UEJsonParser/files/9676956/test.zip)

Using Windows 11 and UE 5.0.3

I am passing in the path E:\test.json

I tried escaping the path with \\ and quotes around the string.

Thanks!

**Comment by besanta** [comment]
Please be sure to use the `Completed` execution pin. The empty execution pin is not async, the file is not loaded at the time it is called.

![2022-09-30 09_29_36-UnitTest](https://user-images.githubusercontent.com/5999616/193216012-e4115b3c-5d3f-43db-9cc1-bb4caab0f2b2.png)
