### ISSUE TITLE
How do I parse array of objects?

### ISSUE THREAD

**Issue by delebash** [besanta/UEJsonParser#3]
I an loading the below string using Create Json Data from string.  But I cannot seem to get the array and loop through the properties.  I think the array is looking for string and not an array of objects.

{
	"test": [
	  {
			"type": "Feature",
			"geometry": {
				"type": "LineString",
				"coordinates": [
					[
						5123724.536459728,
						373803.1006509041
					],
					[
						5124533.580305099,
						373835.5246784863
					],
					[
						5124581.286896712,
						373841.0591644829
					],
					[
						5124623.431366342,
						373856.40447114385
					],
					[
						5124666.075415202,
						373887.47553264996
					],
					[
						5124703.243050124,
						373924.2230822612
					],
					[
						5125096.172159451,
						374420.72184208874
					]
				]
			},
			"properties": {
				"type": "secondary",
				"structure": "none",
				"name_script": "Latin",
				"name": "Touchet N Rd",
				"oneway": "false",
				"class": "secondary",
				"iso_3166_2": "US-WA",
				"len": 11300,
				"iso_3166_1": "US",
				"name_local": "Touchet N Rd"
			},
			"layer": {
				"id": "road-secondary-tertiary",
				"type": "line",
				"source": "composite",
				"source-layer": "road",
				"metadata": {
					"mapbox:group": "1444855786460.0557"
				},
				"filter": [
					"all",
					[
						"match",
						[
							"get",
							"class"
						],
						[
							"secondary",
							"tertiary"
						],
						true,
						false
					],
					[
						"match",
						[
							"get",
							"structure"
						],
						[
							"none",
							"ford"
						],
						true,
						false
					],
					[
						"==",
						[
							"geometry-type"
						],
						"LineString"
					]
				],
				"layout": {
					"line-cap": "round",
					"line-join": "round"
				},
				"paint": {
					"line-width": 5.108705081736628,
					"line-color": {
						"r": 1,
						"g": 1,
						"b": 1,
						"a": 1
					}
				}
			},
			"source": "composite",
			"sourceLayer": "road",
			"state": {}
		},
		{
			"type": "Feature",
			"geometry": {
				"type": "LineString",
				"coordinates": [
					[
						5125010.9962278595,
						374313.10350324836
					],
					[
						5125218.313074685,
						374574.9982009015
					],
					[
						5125265.858207524,
						374608.22950594226
					],
					[
						5125312.077433364,
						374625.7192322744
					],
					[
						5125501.672349444,
						374626.3028314509
					]
				]
			},
			"properties": {
				"type": "secondary",
				"structure": "none",
				"name_script": "Latin",
				"name": "Touchet N Rd",
				"oneway": "false",
				"class": "secondary",
				"iso_3166_2": "US-WA",
				"len": 11300,
				"iso_3166_1": "US",
				"name_local": "Touchet N Rd"
			},
			"layer": {
				"id": "road-secondary-tertiary",
				"type": "line",
				"source": "composite",
				"source-layer": "road",
				"metadata": {
					"mapbox:group": "1444855786460.0557"
				},
				"filter": [
					"all",
					[
						"match",
						[
							"get",
							"class"
						],
						[
							"secondary",
							"tertiary"
						],
						true,
						false
					],
					[
						"match",
						[
							"get",
							"structure"
						],
						[
							"none",
							"ford"
						],
						true,
						false
					],
					[
						"==",
						[
							"geometry-type"
						],
						"LineString"
					]
				],
				"layout": {
					"line-cap": "round",
					"line-join": "round"
				},
				"paint": {
					"line-width": 5.108705081736628,
					"line-color": {
						"r": 1,
						"g": 1,
						"b": 1,
						"a": 1
					}
				}
			},
			"source": "composite",
			"sourceLayer": "road",
			"state": {}
		}
	]
}

**Comment by besanta** [comment]
You have the dedicated function `GetObjectArray`. Use them as you do normally with `ForEachLoop`. 
![2022-09-30 09_36_08-UnitTest](https://user-images.githubusercontent.com/5999616/193216907-2a71bf56-dd28-48c5-9d2a-7722cf4b633b.png)

Cheers
