### ISSUE TITLE
Hello, please help!

### ISSUE THREAD

**Issue by ActivityGames** [besanta/UEJsonParser#4]
Hello
I really liked your plugin, you’re great and I admire you, but I don’t have an understanding of how your syntax works, for example, I have this Json:

{
    "player": {
        "turns_number": {
            "id": 10,
            "name": "Number of turns",
            "type": "int"
        },
        "player_teststat1": {
            "id": 11,
            "name": "player test stat 1",
            "type": "int"
        },
        "player_teststat2": {
            "id": 12,
            "name": "player test stat 2",
            "type": "float"
        }
 }

how can I get the name player_teststat1 from it?

**Comment by ActivityGames** [comment]
I don't understand how I should form the query key text

**Comment by besanta** [comment]
Hello !
You have to use GetObjectField, then GetString like so :
![image](https://github.com/besanta/UEJsonParser/assets/5999616/3888a60e-0c26-40c6-ae93-2fb1ec914010)

**Comment by ActivityGames** [comment]
wow
nice!)

**Comment by ActivityGames** [comment]
wow
nice!)

**Comment by ActivityGames** [comment]
This Plugin support android platform??

**Comment by ActivityGames** [comment]
4.27 ver engine build failed (Android and PC)
![Screenshot_2](https://github.com/besanta/UEJsonParser/assets/7319175/96819548-d341-47f7-8e96-03933fd0243f)

**Comment by besanta** [comment]
Just tried on a fresh 4.27 project with the plugin version from the master branch. Compile + Package. It is working fine
![image](https://github.com/besanta/UEJsonParser/assets/5999616/c0757dc0-3e9a-40a6-9a55-7895c07eafa0)
[JSONTEST427.zip](https://github.com/besanta/UEJsonParser/files/14721503/JSONTEST427.zip)

**Comment by ActivityGames** [comment]
Thank you very much!
And I downloaded the version from Release, from master it works in the assembly

**Comment by besanta** [comment]
Ok then, I close this thread. Don't hesitate to open new ones ;0)
