### ISSUE TITLE
Can't access to HTTP ans Save file nodes in UE 4.26 

### ISSUE THREAD

**Issue by snatch41** [besanta/UEJsonParser#6]
Hi, 

After installing the plugin on my game using 4.26 source engine, I can have access to all blueprint nodes but  the HTTP and Save JSON to file ones.

After contacting Nicolas about that problem I tried to downgrade the EngineAssociation to 4.26 in the UEJsonParser.uproject and rebuild from source with no luck. 

If anybody knows how I can solve that problem, assuming a Engine update is not an option on my project.

Thanks a lot. 

Rémi

**Comment by besanta** [comment]
Are you in a Function on in the EventGraph ? The nodes to load/save files and HTTP are async, you have to be in the EventGraph.

Take a look in the top-right corner, the clock characterize async processes.
![image](https://github.com/user-attachments/assets/b5121dd5-f7d6-45c8-a31d-2f21ad99d716)

**Comment by snatch41** [comment]
I'm in the EventGraph and nodes like Create JSON Data from HTTP got the clock in the top right corner.

**Comment by besanta** [comment]
Everything is looking good here on a 4.26
![image](https://github.com/user-attachments/assets/87023148-4e30-432f-951b-bda377636d73)

I linked a sample project.
[Sample_4_26.zip](https://github.com/user-attachments/files/16506206/Sample_4_26.zip)

**Comment by snatch41** [comment]
Hey Nicolas,

Thanks a lot again for the time you take to solve my problem.
Indeed your 4.26 test works perfectly.
So I guess it comes from my game using 4.26 source.
I haven't changed anything to the source code except to create didecated
servers. Maybe something needs to be added.

Sorry for bothering you in the first place with a problem which in the end
was not related to your plugin but to my source engine.

Have a good day.

Rémi
